<!doctype html>
<html>
    <head>
        <title><?= html($this->title) ?></title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="<?= html($this->description) ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta property="og:title" content="<?= html($this->title) ?>">
        <meta property="og:type" content="website">
        <meta property="og:image"content="<?= html($this->og_image) ?>">
        <meta property="og:site_name" content="<?= html($this->og_sitename) ?>">
        <link rel="stylesheet" href="/css/default/menu.css"/>
        <link rel="stylesheet" href="/css/default/main.css"/>
        <script src='/js/jquery-1.11.1.min.js'></script>
    </head>
    <body class="<?= $this->class ?>">
        <div class="content">
            <div id="main-menu">
                <?= Menu::main() ?>
            </div>
            <?= $this->content ?>
            <? if ($this->footer): ?>
                <div class="footer">
                    <hr>
                    <?= $this->footer ?>
                </div>
            <? endif ?>
        </div>
        <script src='/js/default.js'></script>
    </body>
</html>
